/********************************************************************
* grootutilDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error grootutilDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablegrootutilDict();
extern void G__cpp_setup_inheritancegrootutilDict();
extern void G__cpp_setup_typetablegrootutilDict();
extern void G__cpp_setup_memvargrootutilDict();
extern void G__cpp_setup_globalgrootutilDict();
extern void G__cpp_setup_memfuncgrootutilDict();
extern void G__cpp_setup_funcgrootutilDict();
extern void G__set_cpp_environmentgrootutilDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "grootutil.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__grootutilDictLN_TObject;
extern G__linked_taginfo G__grootutilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__grootutilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__grootutilDictLN_TClassMenuItem;
extern G__linked_taginfo G__grootutilDictLN_grootutil;

/* STUB derived class for protected member access */
