//
// File generated by rootcint at Tue Apr 12 14:57:01 2005.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "grootutilDict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"

#include "TCollectionProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace grootutil {
   namespace ROOT {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void grootutil_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("grootutil", 0 /*version*/, "grootutil.h", 45,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &grootutil_Dictionary, 0);
         return &instance;
      }
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void grootutil_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

/********************************************************
* grootutilDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablegrootutilDict();

extern "C" void G__set_cpp_environmentgrootutilDict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("grootutil.h");
  G__cpp_reset_tagtablegrootutilDict();
}
class G__grootutilDictdOC_tag {};

void* operator new(size_t size,G__grootutilDictdOC_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__grootutilDictdOC_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_grootutilDictdOC() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevgrootutilDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* grootutil */
static int G__grootutilDict_275_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      grootutil::WarnMsgBox((const char*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grootutilDict_275_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      grootutil::AddMenuItem((const char*)G__int(libp->para[0]),(TClassMenuItem*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grootutilDict_275_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)grootutil::FindObject((TObject*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grootutilDict_275_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
   G__letint(result7,85,(long)grootutil::GetPad((TObject*)G__int(libp->para[0]),(TObject*)G__int(libp->para[1])));
      break;
   case 1:
   G__letint(result7,85,(long)grootutil::GetPad((TObject*)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grootutilDict_275_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      grootutil::PaintAllCanvases();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grootutilDict_275_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)grootutil::GetContrastingColor((int)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* grootutil */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncgrootutilDict {
 public:
  G__Sizep2memfuncgrootutilDict() {p=&G__Sizep2memfuncgrootutilDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncgrootutilDict::*p)();
};

size_t G__get_sizep2memfuncgrootutilDict()
{
  G__Sizep2memfuncgrootutilDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancegrootutilDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablegrootutilDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__grootutilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__grootutilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__grootutilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__grootutilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__grootutilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* grootutil */
static void G__setup_memvargrootutil(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__grootutilDictLN_grootutil));
   {
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvargrootutilDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncgrootutil(void) {
   /* grootutil */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__grootutilDictLN_grootutil));
   G__memfunc_setup("WarnMsgBox",1000,G__grootutilDict_275_1_0,121,-1,-1,0,1,1,1,0,"C - - 10 - text",(char*)NULL,(void*)(void (*)(const char*))(&grootutil::WarnMsgBox),0);
   G__memfunc_setup("AddMenuItem",1069,G__grootutilDict_275_2_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - classname U 'TClassMenuItem' - 0 - item",(char*)NULL,(void*)(void (*)(const char*,TClassMenuItem*))(&grootutil::AddMenuItem),0);
   G__memfunc_setup("FindObject",984,G__grootutilDict_275_3_0,85,G__get_linked_tagnum(&G__grootutilDictLN_TObject),-1,0,1,1,1,0,"U 'TObject' - 0 - obj",(char*)NULL,(void*)(TObject* (*)(TObject*))(&grootutil::FindObject),0);
   G__memfunc_setup("GetPad",565,G__grootutilDict_275_4_0,85,G__get_linked_tagnum(&G__grootutilDictLN_TObject),-1,0,2,1,1,0,
"U 'TObject' - 0 - obj U 'TObject' - 0 0 parent",(char*)NULL,(void*)(TObject* (*)(TObject*,TObject*))(&grootutil::GetPad),0);
   G__memfunc_setup("PaintAllCanvases",1609,G__grootutilDict_275_5_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)(void (*)())(&grootutil::PaintAllCanvases),0);
   G__memfunc_setup("GetContrastingColor",1963,G__grootutilDict_275_6_0,105,-1,-1,0,1,1,1,0,"i - - 0 - color",(char*)NULL,(void*)(int (*)(int))(&grootutil::GetContrastingColor),0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncgrootutilDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalgrootutilDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcgrootutilDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__grootutilDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__grootutilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__grootutilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__grootutilDictLN_TClassMenuItem = { "TClassMenuItem" , 99 , -1 };
G__linked_taginfo G__grootutilDictLN_grootutil = { "grootutil" , 110 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablegrootutilDict() {
  G__grootutilDictLN_TObject.tagnum = -1 ;
  G__grootutilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__grootutilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__grootutilDictLN_TClassMenuItem.tagnum = -1 ;
  G__grootutilDictLN_grootutil.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablegrootutilDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__grootutilDictLN_TObject);
   G__get_linked_tagnum(&G__grootutilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__grootutilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__grootutilDictLN_TClassMenuItem);
   G__tagtable_setup(G__get_linked_tagnum(&G__grootutilDictLN_grootutil),0,-1,0,(char*)NULL,G__setup_memvargrootutil,G__setup_memfuncgrootutil);
}
extern "C" void G__cpp_setupgrootutilDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupgrootutilDict()");
  G__set_cpp_environmentgrootutilDict();
  G__cpp_setup_tagtablegrootutilDict();

  G__cpp_setup_inheritancegrootutilDict();

  G__cpp_setup_typetablegrootutilDict();

  G__cpp_setup_memvargrootutilDict();

  G__cpp_setup_memfuncgrootutilDict();
  G__cpp_setup_globalgrootutilDict();
  G__cpp_setup_funcgrootutilDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncgrootutilDict();
  return;
}
class G__cpp_setup_initgrootutilDict {
  public:
    G__cpp_setup_initgrootutilDict() { G__add_setup_func("grootutilDict",(G__incsetup)(&G__cpp_setupgrootutilDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initgrootutilDict() { G__remove_setup_func("grootutilDict"); }
};
G__cpp_setup_initgrootutilDict G__cpp_setup_initializergrootutilDict;

