//
// File generated by rootcint at Tue Apr 12 14:57:08 2005.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "THistListDict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"

#include "TCollectionProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void THistList_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void THistList_Dictionary();
   static TClass *THistList_IsA(const void*);
   static void *new_THistList(void *p = 0);
   static void *newArray_THistList(Long_t size);
   static void delete_THistList(void *p);
   static void deleteArray_THistList(void *p);
   static void destruct_THistList(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::THistList*)
   {
      ::THistList *ptr = 0;
      static ::ROOT::TGenericClassInfo 
         instance("THistList", "THistList.h", 47,
                  typeid(::THistList), DefineBehavior(ptr, ptr),
                  0, &THistList_Dictionary, &THistList_IsA, 0,
                  sizeof(::THistList) );
      instance.SetNew(&new_THistList);
      instance.SetNewArray(&newArray_THistList);
      instance.SetDelete(&delete_THistList);
      instance.SetDeleteArray(&deleteArray_THistList);
      instance.SetDestructor(&destruct_THistList);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::THistList*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void THistList_Dictionary() {
      ::ROOT::GenerateInitInstance((const ::THistList*)0x0)->GetClass();
   }

}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *THistList_IsA(const void *obj) {
      return GetROOT()->GetClass(typeid(*(::THistList*)obj));
   }
   // Wrappers around operator new
   static void *new_THistList(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::THistList : new ::THistList;
   }
   static void *newArray_THistList(Long_t size) {
      return new ::THistList[size];
   }
   // Wrapper around operator delete
   static void delete_THistList(void *p) {
      delete ((::THistList*)p);
   }
   static void deleteArray_THistList(void *p) {
      delete [] ((::THistList*)p);
   }
   static void destruct_THistList(void *p) {
      typedef ::THistList current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::THistList

/********************************************************
* THistListDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableTHistListDict();

extern "C" void G__set_cpp_environmentTHistListDict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("THistList.h");
  G__cpp_reset_tagtableTHistListDict();
}
class G__THistListDictdOC_tag {};

void* operator new(size_t size,G__THistListDictdOC_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__THistListDictdOC_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_THistListDictdOC() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevTHistListDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* THistList */
static int G__THistListDict_329_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   THistList *p=NULL;
   if(G__getaryconstruct()) p=new THistList[G__getaryconstruct()];
   else p=::new((G__THistListDictdOC_tag*)G__getgvp()) THistList;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__THistListDictLN_THistList);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistListDict_329_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((THistList*)(G__getstructoffset()))->Add((TObject*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistListDict_329_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((THistList*)(G__getstructoffset()))->CheckForZombies());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistListDict_329_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((THistList*)(G__getstructoffset()))->Find((TObject*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistListDict_329_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((THistList*)(G__getstructoffset()))->Remove((TObject*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef THistList G__TTHistList;
static int G__THistListDict_329_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (THistList *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         ((THistList *)((G__getstructoffset())+sizeof(THistList)*i))->~G__TTHistList();
   else {
     long G__Xtmp=G__getgvp();
     G__setgvp(G__PVOID);
     ((THistList *)(G__getstructoffset()))->~G__TTHistList();
     G__setgvp(G__Xtmp);
     G__operator_delete((void*)G__getstructoffset());
   }
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* THistList */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTHistListDict {
 public:
  G__Sizep2memfuncTHistListDict() {p=&G__Sizep2memfuncTHistListDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTHistListDict::*p)();
};

size_t G__get_sizep2memfuncTHistListDict()
{
  G__Sizep2memfuncTHistListDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTHistListDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTHistListDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__THistListDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__THistListDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THistListDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__THistListDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THistListDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* THistList */
static void G__setup_memvarTHistList(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__THistListDictLN_THistList));
   { THistList *p; p=(THistList*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__THistListDictLN_TList),-1,-1,4,"fList=",0,"List containing histogrators");
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,4,"fMaxID=",0,"Incremented by one whenever a histogrator is added");
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTHistListDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTHistList(void) {
   /* THistList */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__THistListDictLN_THistList));
   G__memfunc_setup("THistList",904,G__THistListDict_329_1_0,105,G__get_linked_tagnum(&G__THistListDictLN_THistList),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Add",265,G__THistListDict_329_2_0,103,-1,-1,0,1,1,1,0,"U 'TObject' - 0 - hist",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CheckForZombies",1502,G__THistListDict_329_3_0,103,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Find",385,G__THistListDict_329_4_0,85,G__get_linked_tagnum(&G__THistListDictLN_THistogrator),-1,0,1,1,1,0,"U 'TObject' - 0 - hist",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Remove",622,G__THistListDict_329_5_0,103,-1,-1,0,1,1,1,0,"U 'TObject' - 0 - hist",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~THistList",1030,G__THistListDict_329_6_0,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTHistListDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTHistListDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTHistListDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__THistListDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__THistListDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__THistListDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__THistListDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__THistListDictLN_THistogrator = { "THistogrator" , 99 , -1 };
G__linked_taginfo G__THistListDictLN_THistList = { "THistList" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTHistListDict() {
  G__THistListDictLN_TObject.tagnum = -1 ;
  G__THistListDictLN_TList.tagnum = -1 ;
  G__THistListDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__THistListDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__THistListDictLN_THistogrator.tagnum = -1 ;
  G__THistListDictLN_THistList.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTHistListDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__THistListDictLN_TObject);
   G__get_linked_tagnum(&G__THistListDictLN_TList);
   G__get_linked_tagnum(&G__THistListDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__THistListDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__THistListDictLN_THistogrator);
   G__tagtable_setup(G__get_linked_tagnum(&G__THistListDictLN_THistList),sizeof(THistList),-1,256,(char*)NULL,G__setup_memvarTHistList,G__setup_memfuncTHistList);
}
extern "C" void G__cpp_setupTHistListDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTHistListDict()");
  G__set_cpp_environmentTHistListDict();
  G__cpp_setup_tagtableTHistListDict();

  G__cpp_setup_inheritanceTHistListDict();

  G__cpp_setup_typetableTHistListDict();

  G__cpp_setup_memvarTHistListDict();

  G__cpp_setup_memfuncTHistListDict();
  G__cpp_setup_globalTHistListDict();
  G__cpp_setup_funcTHistListDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTHistListDict();
  return;
}
class G__cpp_setup_initTHistListDict {
  public:
    G__cpp_setup_initTHistListDict() { G__add_setup_func("THistListDict",(G__incsetup)(&G__cpp_setupTHistListDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTHistListDict() { G__remove_setup_func("THistListDict"); }
};
G__cpp_setup_initTHistListDict G__cpp_setup_initializerTHistListDict;

