//
// File generated by rootcint at Tue Apr 12 14:56:13 2005.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "THistograteUtilDict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"

#include "TCollectionProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void THistograteUtil_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *THistograteUtil_IsA(const void*);
   static void *new_THistograteUtil(void *p = 0);
   static void *newArray_THistograteUtil(Long_t size);
   static void delete_THistograteUtil(void *p);
   static void deleteArray_THistograteUtil(void *p);
   static void destruct_THistograteUtil(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::THistograteUtil*)
   {
      ::THistograteUtil *ptr = 0;
      static ::ROOT::TGenericClassInfo 
         instance("THistograteUtil", ::THistograteUtil::Class_Version(), "THistograteUtil.h", 44,
                  typeid(::THistograteUtil), DefineBehavior(ptr, ptr),
                  &::THistograteUtil::Dictionary, &THistograteUtil_IsA, 0,
                  sizeof(::THistograteUtil) );
      instance.SetNew(&new_THistograteUtil);
      instance.SetNewArray(&newArray_THistograteUtil);
      instance.SetDelete(&delete_THistograteUtil);
      instance.SetDeleteArray(&deleteArray_THistograteUtil);
      instance.SetDestructor(&destruct_THistograteUtil);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::THistograteUtil*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *THistograteUtil::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *THistograteUtil::Class_Name()
{
   return "THistograteUtil";
}

//______________________________________________________________________________
const char *THistograteUtil::ImplFileName()
{
   return ::ROOT::GenerateInitInstance((const ::THistograteUtil*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int THistograteUtil::ImplFileLine()
{
   return ::ROOT::GenerateInitInstance((const ::THistograteUtil*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void THistograteUtil::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstance((const ::THistograteUtil*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *THistograteUtil::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstance((const ::THistograteUtil*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void THistograteUtil::Streamer(TBuffer &R__b)
{
   // Stream an object of class THistograteUtil.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b.StreamObject(&(fHistList),typeid(THistList));
      R__b.CheckByteCount(R__s, R__c, THistograteUtil::IsA());
   } else {
      R__c = R__b.WriteVersion(THistograteUtil::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b.StreamObject(&(fHistList),typeid(THistList));
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void THistograteUtil::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class THistograteUtil.

      TClass *R__cl = ::THistograteUtil::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fHistList", (void*)&fHistList);
      ::ROOT::GenericShowMembers("THistList", (void*)&fHistList, R__insp, strcat(R__parent,"fHistList."),false);
      R__parent[R__ncp] = 0;
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *THistograteUtil_IsA(const void *obj) {
      return ((::THistograteUtil*)obj)->IsA();
   }
   // Wrappers around operator new
   static void *new_THistograteUtil(void *p) {
      return  p ? new(p) ::THistograteUtil : new ::THistograteUtil;
   }
   static void *newArray_THistograteUtil(Long_t size) {
      return new ::THistograteUtil[size];
   }
   // Wrapper around operator delete
   static void delete_THistograteUtil(void *p) {
      delete ((::THistograteUtil*)p);
   }
   static void deleteArray_THistograteUtil(void *p) {
      delete [] ((::THistograteUtil*)p);
   }
   static void destruct_THistograteUtil(void *p) {
      typedef ::THistograteUtil current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::THistograteUtil

/********************************************************
* THistograteUtilDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableTHistograteUtilDict();

extern "C" void G__set_cpp_environmentTHistograteUtilDict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("THistograteUtil.h");
  G__cpp_reset_tagtableTHistograteUtilDict();
}
class G__THistograteUtilDictdOC_tag {};

void* operator new(size_t size,G__THistograteUtilDictdOC_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__THistograteUtilDictdOC_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_THistograteUtilDictdOC() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevTHistograteUtilDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* THistograteUtil */
static int G__THistograteUtilDict_330_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   THistograteUtil *p=NULL;
   if(G__getaryconstruct()) p=new THistograteUtil[G__getaryconstruct()];
   else                    p=new THistograteUtil;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__THistograteUtilDictLN_THistograteUtil);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->AddMenu();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->HistDelete((TObject*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->PaveDelete((TObject*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->CutDelete((TObject*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->HistAddCut((const char*)G__int(libp->para[0]),(TObject*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->HistFillAttributes((TObject*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->HistLineAttributes((TObject*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->Histograte((TObject*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->Unimplemented((TObject*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)THistograteUtil::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistograteUtil::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)THistograteUtil::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      THistograteUtil::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const THistograteUtil*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistograteUtil*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistograteUtil::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)THistograteUtil::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistograteUtil::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistograteUtilDict_330_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)THistograteUtil::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef THistograteUtil G__TTHistograteUtil;
static int G__THistograteUtilDict_330_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (THistograteUtil *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (THistograteUtil *)((G__getstructoffset())+sizeof(THistograteUtil)*i);
   else  delete (THistograteUtil *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* THistograteUtil */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTHistograteUtilDict {
 public:
  G__Sizep2memfuncTHistograteUtilDict() {p=&G__Sizep2memfuncTHistograteUtilDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTHistograteUtilDict::*p)();
};

size_t G__get_sizep2memfuncTHistograteUtilDict()
{
  G__Sizep2memfuncTHistograteUtilDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTHistograteUtilDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__THistograteUtilDictLN_THistograteUtil))) {
     THistograteUtil *G__Lderived;
     G__Lderived=(THistograteUtil*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistograteUtilDictLN_THistograteUtil),G__get_linked_tagnum(&G__THistograteUtilDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTHistograteUtilDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__THistograteUtilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__THistograteUtilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THistograteUtilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__THistograteUtilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THistograteUtilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* THistograteUtil */
static void G__setup_memvarTHistograteUtil(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__THistograteUtilDictLN_THistograteUtil));
   { THistograteUtil *p; p=(THistograteUtil*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__THistograteUtilDictLN_THistList),-1,-1,4,"fHistList=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistograteUtilDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTHistograteUtilDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTHistograteUtil(void) {
   /* THistograteUtil */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__THistograteUtilDictLN_THistograteUtil));
   G__memfunc_setup("THistograteUtil",1548,G__THistograteUtilDict_330_1_0,105,G__get_linked_tagnum(&G__THistograteUtilDictLN_THistograteUtil),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AddMenu",670,G__THistograteUtilDict_330_2_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("HistDelete",1003,G__THistograteUtilDict_330_3_0,121,-1,-1,0,1,1,1,0,"U 'TObject' - 0 - hist",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("PaveDelete",991,G__THistograteUtilDict_330_4_0,121,-1,-1,0,1,1,1,0,"U 'TObject' - 0 - pave",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CutDelete",895,G__THistograteUtilDict_330_5_0,121,-1,-1,0,1,1,1,0,"U 'TObject' - 0 - cut",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("HistAddCut",973,G__THistograteUtilDict_330_6_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - cutname U 'TObject' - 0 - hist",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("HistFillAttributes",1862,G__THistograteUtilDict_330_7_0,121,-1,-1,0,1,1,1,0,"U 'TObject' - 0 - hist",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("HistLineAttributes",1863,G__THistograteUtilDict_330_8_0,121,-1,-1,0,1,1,1,0,"U 'TObject' - 0 - hist",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Histograte",1050,G__THistograteUtilDict_330_9_0,121,-1,-1,0,1,1,1,0,"U 'TObject' - 0 - hist",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Unimplemented",1367,G__THistograteUtilDict_330_0_1,121,-1,-1,0,1,1,1,0,"U 'TObject' - 0 - obj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AddClassMenus",1287,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"C - - 10 - classname",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AddCutMenuItem",1369,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__THistograteUtilDictLN_TClassMenuItem),-1,0,1,1,4,0,"C - - 10 - classname",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DelMenuItem",1081,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__THistograteUtilDictLN_TClassMenuItem),-1,0,1,1,4,0,"C - - 10 - classname",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("FillMenuItem",1195,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__THistograteUtilDictLN_TClassMenuItem),-1,0,1,1,4,0,"C - - 10 - classname",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("LineMenuItem",1196,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__THistograteUtilDictLN_TClassMenuItem),-1,0,1,1,4,0,"C - - 10 - classname",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SeparatorMenuItem",1749,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__THistograteUtilDictLN_TClassMenuItem),-1,0,1,1,4,0,"C - - 10 - classname",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("StartMenuItem",1330,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__THistograteUtilDictLN_TClassMenuItem),-1,0,1,1,4,0,"C - - 10 - classname",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("UnimplMenuItem",1433,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__THistograteUtilDictLN_TClassMenuItem),-1,0,2,1,4,0,
"C - - 10 - classname C - - 10 - title",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__THistograteUtilDict_330_9_1,85,G__get_linked_tagnum(&G__THistograteUtilDictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)(TClass* (*)())(&THistograteUtil::Class),0);
   G__memfunc_setup("Class_Name",982,G__THistograteUtilDict_330_0_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistograteUtil::Class_Name),0);
   G__memfunc_setup("Class_Version",1339,G__THistograteUtilDict_330_1_2,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)(Version_t (*)())(&THistograteUtil::Class_Version),0);
   G__memfunc_setup("Dictionary",1046,G__THistograteUtilDict_330_2_2,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(void (*)())(&THistograteUtil::Dictionary),0);
   G__memfunc_setup("IsA",253,G__THistograteUtilDict_330_3_2,85,G__get_linked_tagnum(&G__THistograteUtilDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__THistograteUtilDict_330_4_2,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__THistograteUtilDict_330_5_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__THistograteUtilDict_330_6_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__THistograteUtilDict_330_7_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistograteUtil::DeclFileName),0);
   G__memfunc_setup("ImplFileLine",1178,G__THistograteUtilDict_330_8_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&THistograteUtil::ImplFileLine),0);
   G__memfunc_setup("ImplFileName",1171,G__THistograteUtilDict_330_9_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistograteUtil::ImplFileName),0);
   G__memfunc_setup("DeclFileLine",1152,G__THistograteUtilDict_330_0_3,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&THistograteUtil::DeclFileLine),0);
   // automatic destructor
   G__memfunc_setup("~THistograteUtil",1674,G__THistograteUtilDict_330_1_3,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTHistograteUtilDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTHistograteUtilDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTHistograteUtilDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__THistograteUtilDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__THistograteUtilDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__THistograteUtilDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__THistograteUtilDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__THistograteUtilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__THistograteUtilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__THistograteUtilDictLN_TClassMenuItem = { "TClassMenuItem" , 99 , -1 };
G__linked_taginfo G__THistograteUtilDictLN_THistList = { "THistList" , 99 , -1 };
G__linked_taginfo G__THistograteUtilDictLN_THistograteUtil = { "THistograteUtil" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTHistograteUtilDict() {
  G__THistograteUtilDictLN_TClass.tagnum = -1 ;
  G__THistograteUtilDictLN_TBuffer.tagnum = -1 ;
  G__THistograteUtilDictLN_TMemberInspector.tagnum = -1 ;
  G__THistograteUtilDictLN_TObject.tagnum = -1 ;
  G__THistograteUtilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__THistograteUtilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__THistograteUtilDictLN_TClassMenuItem.tagnum = -1 ;
  G__THistograteUtilDictLN_THistList.tagnum = -1 ;
  G__THistograteUtilDictLN_THistograteUtil.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTHistograteUtilDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__THistograteUtilDictLN_TClass);
   G__get_linked_tagnum(&G__THistograteUtilDictLN_TBuffer);
   G__get_linked_tagnum(&G__THistograteUtilDictLN_TMemberInspector);
   G__get_linked_tagnum(&G__THistograteUtilDictLN_TObject);
   G__get_linked_tagnum(&G__THistograteUtilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__THistograteUtilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__THistograteUtilDictLN_TClassMenuItem);
   G__get_linked_tagnum(&G__THistograteUtilDictLN_THistList);
   G__tagtable_setup(G__get_linked_tagnum(&G__THistograteUtilDictLN_THistograteUtil),sizeof(THistograteUtil),-1,28928,(char*)NULL,G__setup_memvarTHistograteUtil,G__setup_memfuncTHistograteUtil);
}
extern "C" void G__cpp_setupTHistograteUtilDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTHistograteUtilDict()");
  G__set_cpp_environmentTHistograteUtilDict();
  G__cpp_setup_tagtableTHistograteUtilDict();

  G__cpp_setup_inheritanceTHistograteUtilDict();

  G__cpp_setup_typetableTHistograteUtilDict();

  G__cpp_setup_memvarTHistograteUtilDict();

  G__cpp_setup_memfuncTHistograteUtilDict();
  G__cpp_setup_globalTHistograteUtilDict();
  G__cpp_setup_funcTHistograteUtilDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTHistograteUtilDict();
  return;
}
class G__cpp_setup_initTHistograteUtilDict {
  public:
    G__cpp_setup_initTHistograteUtilDict() { G__add_setup_func("THistograteUtilDict",(G__incsetup)(&G__cpp_setupTHistograteUtilDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTHistograteUtilDict() { G__remove_setup_func("THistograteUtilDict"); }
};
G__cpp_setup_initTHistograteUtilDict G__cpp_setup_initializerTHistograteUtilDict;

