//
// File generated by rootcint at Tue Apr 12 14:57:13 2005.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "THistogratorDict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"

#include "TCollectionProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void THistogrator_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *THistogrator_IsA(const void*);
   static void *new_THistogrator(void *p = 0);
   static void *newArray_THistogrator(Long_t size);
   static void delete_THistogrator(void *p);
   static void deleteArray_THistogrator(void *p);
   static void destruct_THistogrator(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::THistogrator*)
   {
      ::THistogrator *ptr = 0;
      static ::ROOT::TGenericClassInfo 
         instance("THistogrator", ::THistogrator::Class_Version(), "THistogrator.h", 50,
                  typeid(::THistogrator), DefineBehavior(ptr, ptr),
                  &::THistogrator::Dictionary, &THistogrator_IsA, 0,
                  sizeof(::THistogrator) );
      instance.SetNew(&new_THistogrator);
      instance.SetNewArray(&newArray_THistogrator);
      instance.SetDelete(&delete_THistogrator);
      instance.SetDeleteArray(&deleteArray_THistogrator);
      instance.SetDestructor(&destruct_THistogrator);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::THistogrator*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *THistogrator::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *THistogrator::Class_Name()
{
   return "THistogrator";
}

//______________________________________________________________________________
const char *THistogrator::ImplFileName()
{
   return ::ROOT::GenerateInitInstance((const ::THistogrator*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int THistogrator::ImplFileLine()
{
   return ::ROOT::GenerateInitInstance((const ::THistogrator*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void THistogrator::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstance((const ::THistogrator*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *THistogrator::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstance((const ::THistogrator*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void THistogrator::Streamer(TBuffer &R__b)
{
   // Stream an object of class THistogrator.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      TAttFill::Streamer(R__b);
      TAttLine::Streamer(R__b);
      fQObject.Streamer(R__b);
      R__b >> fAssocHist;
      R__b >> fCanvas;
      R__b >> fCut;
      R__b >> fHist;
      R__b >> fPad;
      R__b >> (Int_t&)fState;
      R__b >> fStats;
      R__b.CheckByteCount(R__s, R__c, THistogrator::IsA());
   } else {
      R__c = R__b.WriteVersion(THistogrator::IsA(), kTRUE);
      TObject::Streamer(R__b);
      TAttFill::Streamer(R__b);
      TAttLine::Streamer(R__b);
      fQObject.Streamer(R__b);
      R__b << fAssocHist;
      R__b << fCanvas;
      R__b << fCut;
      R__b << fHist;
      R__b << fPad;
      R__b << (Int_t)fState;
      R__b << fStats;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void THistogrator::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class THistogrator.

      TClass *R__cl = ::THistogrator::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fQObject", &fQObject);
      fQObject.ShowMembers(R__insp, strcat(R__parent,"fQObject.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "*fAssocHist", &fAssocHist);
      R__insp.Inspect(R__cl, R__parent, "*fCanvas", &fCanvas);
      R__insp.Inspect(R__cl, R__parent, "*fCut", &fCut);
      R__insp.Inspect(R__cl, R__parent, "*fHist", &fHist);
      R__insp.Inspect(R__cl, R__parent, "*fPad", &fPad);
      R__insp.Inspect(R__cl, R__parent, "fState", &fState);
      R__insp.Inspect(R__cl, R__parent, "*fStats", &fStats);
      TObject::ShowMembers(R__insp, R__parent);
      TAttFill::ShowMembers(R__insp, R__parent);
      TAttLine::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *THistogrator_IsA(const void *obj) {
      return ((::THistogrator*)obj)->IsA();
   }
   // Wrappers around operator new
   static void *new_THistogrator(void *p) {
      return  p ? new(p) ::THistogrator : new ::THistogrator;
   }
   static void *newArray_THistogrator(Long_t size) {
      return new ::THistogrator[size];
   }
   // Wrapper around operator delete
   static void delete_THistogrator(void *p) {
      delete ((::THistogrator*)p);
   }
   static void deleteArray_THistogrator(void *p) {
      delete [] ((::THistogrator*)p);
   }
   static void destruct_THistogrator(void *p) {
      typedef ::THistogrator current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::THistogrator

/********************************************************
* THistogratorDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableTHistogratorDict();

extern "C" void G__set_cpp_environmentTHistogratorDict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("THistogrator.h");
  G__cpp_reset_tagtableTHistogratorDict();
}
class G__THistogratorDictdOC_tag {};

void* operator new(size_t size,G__THistogratorDictdOC_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__THistogratorDictdOC_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_THistogratorDictdOC() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevTHistogratorDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* THistogrator */
static int G__THistogratorDict_313_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const THistogrator*)(G__getstructoffset()))->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((THistogrator*)(G__getstructoffset()))->Connect((const char*)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(void*)G__int(libp->para[2]),(const char*)G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 3:
      G__letint(result7,103,(long)((THistogrator*)(G__getstructoffset()))->Disconnect((const char*)G__int(libp->para[0]),(void*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7,103,(long)((THistogrator*)(G__getstructoffset()))->Disconnect((const char*)G__int(libp->para[0]),(void*)G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7,103,(long)((THistogrator*)(G__getstructoffset()))->Disconnect((const char*)G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7,103,(long)((THistogrator*)(G__getstructoffset()))->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->HighPriority((const char*)G__int(libp->para[0]),(const char*)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->HighPriority((const char*)G__int(libp->para[0]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->LowPriority((const char*)G__int(libp->para[0]),(const char*)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->LowPriority((const char*)G__int(libp->para[0]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(const char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Long_t*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Double_t)G__double(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Long_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),*((Long64_t*)G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),*((ULong64_t*)G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Bool_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Char_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(UChar_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Short_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(UShort_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(ULong_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Float_t)G__double(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Destroyed();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->ChangedBy((const char*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Message((const char*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   THistogrator *p=NULL;
   if(G__getaryconstruct()) p=new THistogrator[G__getaryconstruct()];
   else                    p=new THistogrator;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   THistogrator *p=NULL;
      p = new THistogrator(
(const char*)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(TH1*)G__int(libp->para[2]),(TH1*)G__int(libp->para[3]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((THistogrator*)(G__getstructoffset()))->CheckIfZombie());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->DelAssocHist();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->DelCut();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Delete();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->DelHist();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_2_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->DelPave();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_3_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->ExecuteButton1Up((double)G__double(libp->para[0]),(double)G__double(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_4_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->ExecuteClosed();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_5_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->ExecuteKey();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_6_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->ExecuteMotion((double)G__double(libp->para[0]),(double)G__double(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_7_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((THistogrator*)(G__getstructoffset()))->GetAssocHist());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_8_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((THistogrator*)(G__getstructoffset()))->GetCut());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_9_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((THistogrator*)(G__getstructoffset()))->GetHist());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_0_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((THistogrator*)(G__getstructoffset()))->GetPave());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_1_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((THistogrator*)(G__getstructoffset()))->GetPoly((TObject*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_2_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->GotClosed();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_3_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->GotMouseEvent((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(TObject*)G__int(libp->para[3]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_4_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Paint();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_5_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->SetCut(*(TCutG*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_6_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->SetFillColor((Color_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_7_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->SetFillStyle((Style_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_8_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->SetLineColor((Color_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_9_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->SetLineStyle((Style_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_0_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)THistogrator::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_1_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistogrator::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_2_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)THistogrator::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_3_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      THistogrator::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_4_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const THistogrator*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_5_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_6_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_7_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_8_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistogrator::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_9_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)THistogrator::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_0_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistogrator::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogratorDict_313_1_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)THistogrator::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__THistogratorDict_313_2_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   THistogrator *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new THistogrator(*(THistogrator*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef THistogrator G__TTHistogrator;
static int G__THistogratorDict_313_3_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (THistogrator *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (THistogrator *)((G__getstructoffset())+sizeof(THistogrator)*i);
   else  delete (THistogrator *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__THistogratorDict_313_4_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   THistogrator *dest = (THistogrator*)(G__getstructoffset());
   *dest = (*(THistogrator*)libp->para[0].ref);
   const THistogrator& obj = *dest;
   result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* THistogrator */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTHistogratorDict {
 public:
  G__Sizep2memfuncTHistogratorDict() {p=&G__Sizep2memfuncTHistogratorDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTHistogratorDict::*p)();
};

size_t G__get_sizep2memfuncTHistogratorDict()
{
  G__Sizep2memfuncTHistogratorDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTHistogratorDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator))) {
     THistogrator *G__Lderived;
     G__Lderived=(THistogrator*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator),G__get_linked_tagnum(&G__THistogratorDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TAttFill *G__Lpbase=(TAttFill*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator),G__get_linked_tagnum(&G__THistogratorDictLN_TAttFill),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TAttLine *G__Lpbase=(TAttLine*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator),G__get_linked_tagnum(&G__THistogratorDictLN_TAttLine),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTHistogratorDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,
-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,
-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,
-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,
-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,
-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,
-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,
-1);
   G__setnewtype(-1,"Signed long integer 4 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,
-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,
-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,
-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,
-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Long64_t",117,G__get_linked_tagnum(&G__THistogratorDictLN_G__longlong),0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",117,G__get_linked_tagnum(&G__THistogratorDictLN_G__ulonglong),0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__THistogratorDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__THistogratorDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THistogratorDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__THistogratorDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THistogratorDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("Style_t",115,-1,0,
-1);
   G__setnewtype(-1,"Style number (short)",0);
   G__search_typename2("Color_t",115,-1,0,
-1);
   G__setnewtype(-1,"Color number (short)",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* THistogrator */
static void G__setup_memvarTHistogrator(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator));
   { THistogrator *p; p=(THistogrator*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__THistogratorDictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistogratorDictLN_TH1),-1,-1,2,"fAssocHist=",0,"Histogram which is to be integrated");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistogratorDictLN_TCanvas),-1,-1,2,"fCanvas=",0,"Canvas containing associated histogram");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistogratorDictLN_TCutG),-1,-1,2,"fCut=",0,"Graphical cut");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistogratorDictLN_TH1),-1,-1,2,"fHist=",0,"Histogram used to draw the shaded area");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistogratorDictLN_TPad),-1,-1,2,"fPad=",0,"Pad containing associated histogram");
   G__memvar_setup((void*)NULL,105,0,0,G__get_linked_tagnum(&G__THistogratorDictLN_State_t),-1,-1,2,"fState=",0,"Internal state of histogrator");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistogratorDictLN_TPaveStats),-1,-1,2,"fStats=",0,"Stats box for displaying integral and sum");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistogratorDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTHistogratorDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTHistogrator(void) {
   /* THistogrator */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator));
   G__memfunc_setup("GetListOfSignals",1602,G__THistogratorDict_313_1_0,85,G__get_linked_tagnum(&G__THistogratorDictLN_TList),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Connect",714,G__THistogratorDict_313_2_0,103,-1,G__defined_typename("Bool_t"),0,4,1,1,0,
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Disconnect",1034,G__THistogratorDict_313_3_0,103,-1,G__defined_typename("Bool_t"),0,3,1,1,0,
"C - - 10 0 sig Y - - 0 0 rcvr "
"C - - 10 0 slt",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("HighPriority",1250,G__THistogratorDict_313_4_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal_name C - - 10 0 slot_name",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("LowPriority",1172,G__THistogratorDict_313_5_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal_name C - - 10 0 slot_name",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_6_0,121,-1,-1,0,1,1,1,0,"C - - 10 - signal",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_7_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal C - - 10 - params",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_8_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal L - 'Long_t' 0 - paramArr",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_9_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal d - 'Double_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_0_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal l - 'Long_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_1_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal u 'G__longlong' 'Long64_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_2_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal u 'G__ulonglong' 'ULong64_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_3_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal g - 'Bool_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_4_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal c - 'Char_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_5_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal b - 'UChar_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_6_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal s - 'Short_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_7_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal r - 'UShort_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_8_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal i - 'Int_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_9_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal h - 'UInt_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_0_2,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal k - 'ULong_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__THistogratorDict_313_1_2,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal f - 'Float_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Destroyed",947,G__THistogratorDict_313_2_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ChangedBy",869,G__THistogratorDict_313_3_2,121,-1,-1,0,1,1,1,0,"C - - 10 - method",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Message",709,G__THistogratorDict_313_4_2,121,-1,-1,0,1,1,1,0,"C - - 10 - msg",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("THistogrator",1258,G__THistogratorDict_313_5_2,105,G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("THistogrator",1258,G__THistogratorDict_313_6_2,105,G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator),-1,0,4,1,1,0,
"C - - 10 - name C - - 10 - title "
"U 'TH1' - 0 - h U 'TH1' - 0 - ah",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CheckIfZombie",1267,G__THistogratorDict_313_7_2,103,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DelAssocHist",1190,G__THistogratorDict_313_8_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DelCut",577,G__THistogratorDict_313_9_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Delete",595,G__THistogratorDict_313_0_3,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DelHist",685,G__THistogratorDict_313_1_3,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DelPave",673,G__THistogratorDict_313_2_3,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteButton1Up",1605,G__THistogratorDict_313_3_3,121,-1,-1,0,2,1,1,0,
"d - - 0 - padx d - - 0 - pady",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteClosed",1325,G__THistogratorDict_313_4_3,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteKey",1020,G__THistogratorDict_313_5_3,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteMotion",1353,G__THistogratorDict_313_6_3,121,-1,-1,0,2,1,1,0,
"d - - 0 - padx d - - 0 - pady",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetAssocHist",1201,G__THistogratorDict_313_7_3,85,G__get_linked_tagnum(&G__THistogratorDictLN_TH1),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetCut",588,G__THistogratorDict_313_8_3,85,G__get_linked_tagnum(&G__THistogratorDictLN_TCutG),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetHist",696,G__THistogratorDict_313_9_3,85,G__get_linked_tagnum(&G__THistogratorDictLN_TH1),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetPave",684,G__THistogratorDict_313_0_4,85,G__get_linked_tagnum(&G__THistogratorDictLN_TPaveStats),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetPoly",708,G__THistogratorDict_313_1_4,85,G__get_linked_tagnum(&G__THistogratorDictLN_TPolyLine),-1,0,1,1,1,0,"U 'TObject' - 0 - p",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GotClosed",900,G__THistogratorDict_313_2_4,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GotMouseEvent",1333,G__THistogratorDict_313_3_4,121,-1,-1,0,4,1,1,0,
"i - 'Int_t' 0 - evt i - 'Int_t' 0 - x "
"i - 'Int_t' 0 - y U 'TObject' - 0 - sel",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Paint",508,G__THistogratorDict_313_4_4,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetCut",600,G__THistogratorDict_313_5_4,121,-1,-1,0,1,1,1,0,"u 'TCutG' - 11 - cut",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetFillColor",1202,G__THistogratorDict_313_6_4,121,-1,-1,0,1,1,1,0,"s - 'Color_t' 0 - fcolor",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetFillStyle",1220,G__THistogratorDict_313_7_4,121,-1,-1,0,1,1,1,0,"s - 'Style_t' 0 - fstyle",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetLineColor",1203,G__THistogratorDict_313_8_4,121,-1,-1,0,1,1,1,0,"s - 'Color_t' 0 - lcolor",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetLineStyle",1221,G__THistogratorDict_313_9_4,121,-1,-1,0,1,1,1,0,"s - 'Style_t' 0 - lstyle",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Class",502,G__THistogratorDict_313_0_5,85,G__get_linked_tagnum(&G__THistogratorDictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)(TClass* (*)())(&THistogrator::Class),0);
   G__memfunc_setup("Class_Name",982,G__THistogratorDict_313_1_5,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistogrator::Class_Name),0);
   G__memfunc_setup("Class_Version",1339,G__THistogratorDict_313_2_5,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)(Version_t (*)())(&THistogrator::Class_Version),0);
   G__memfunc_setup("Dictionary",1046,G__THistogratorDict_313_3_5,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(void (*)())(&THistogrator::Dictionary),0);
   G__memfunc_setup("IsA",253,G__THistogratorDict_313_4_5,85,G__get_linked_tagnum(&G__THistogratorDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__THistogratorDict_313_5_5,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__THistogratorDict_313_6_5,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__THistogratorDict_313_7_5,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__THistogratorDict_313_8_5,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistogrator::DeclFileName),0);
   G__memfunc_setup("ImplFileLine",1178,G__THistogratorDict_313_9_5,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&THistogrator::ImplFileLine),0);
   G__memfunc_setup("ImplFileName",1171,G__THistogratorDict_313_0_6,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistogrator::ImplFileName),0);
   G__memfunc_setup("DeclFileLine",1152,G__THistogratorDict_313_1_6,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&THistogrator::DeclFileLine),0);
   // automatic copy constructor
   G__memfunc_setup("THistogrator",1258,G__THistogratorDict_313_2_6,(int)('i'),G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator),-1,0,1,1,1,0,"u 'THistogrator' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~THistogrator",1384,G__THistogratorDict_313_3_6,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic assignment operator
   G__memfunc_setup("operator=",937,G__THistogratorDict_313_4_6,(int)('u'),G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator),-1,1,1,1,1,0,"u 'THistogrator' - 11 - -",(char*)NULL,(void*)NULL,0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTHistogratorDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTHistogratorDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTHistogratorDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__THistogratorDictLN_G__ulonglong = { "G__ulonglong" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_G__longlong = { "G__longlong" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TAttFill = { "TAttFill" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TAttLine = { "TAttLine" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TPad = { "TPad" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TCutG = { "TCutG" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TPaveStats = { "TPaveStats" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_TPolyLine = { "TPolyLine" , 99 , -1 };
G__linked_taginfo G__THistogratorDictLN_State_t = { "State_t" , 101 , -1 };
G__linked_taginfo G__THistogratorDictLN_THistogrator = { "THistogrator" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTHistogratorDict() {
  G__THistogratorDictLN_G__ulonglong.tagnum = -1 ;
  G__THistogratorDictLN_G__longlong.tagnum = -1 ;
  G__THistogratorDictLN_TClass.tagnum = -1 ;
  G__THistogratorDictLN_TBuffer.tagnum = -1 ;
  G__THistogratorDictLN_TMemberInspector.tagnum = -1 ;
  G__THistogratorDictLN_TObject.tagnum = -1 ;
  G__THistogratorDictLN_TList.tagnum = -1 ;
  G__THistogratorDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__THistogratorDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__THistogratorDictLN_TAttFill.tagnum = -1 ;
  G__THistogratorDictLN_TAttLine.tagnum = -1 ;
  G__THistogratorDictLN_TQObjSender.tagnum = -1 ;
  G__THistogratorDictLN_TCanvas.tagnum = -1 ;
  G__THistogratorDictLN_TPad.tagnum = -1 ;
  G__THistogratorDictLN_TH1.tagnum = -1 ;
  G__THistogratorDictLN_TCutG.tagnum = -1 ;
  G__THistogratorDictLN_TPaveStats.tagnum = -1 ;
  G__THistogratorDictLN_TPolyLine.tagnum = -1 ;
  G__THistogratorDictLN_State_t.tagnum = -1 ;
  G__THistogratorDictLN_THistogrator.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTHistogratorDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__THistogratorDictLN_G__ulonglong);
   G__get_linked_tagnum(&G__THistogratorDictLN_G__longlong);
   G__get_linked_tagnum(&G__THistogratorDictLN_TClass);
   G__get_linked_tagnum(&G__THistogratorDictLN_TBuffer);
   G__get_linked_tagnum(&G__THistogratorDictLN_TMemberInspector);
   G__get_linked_tagnum(&G__THistogratorDictLN_TObject);
   G__get_linked_tagnum(&G__THistogratorDictLN_TList);
   G__get_linked_tagnum(&G__THistogratorDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__THistogratorDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__THistogratorDictLN_TAttFill);
   G__get_linked_tagnum(&G__THistogratorDictLN_TAttLine);
   G__get_linked_tagnum(&G__THistogratorDictLN_TQObjSender);
   G__get_linked_tagnum(&G__THistogratorDictLN_TCanvas);
   G__get_linked_tagnum(&G__THistogratorDictLN_TPad);
   G__get_linked_tagnum(&G__THistogratorDictLN_TH1);
   G__get_linked_tagnum(&G__THistogratorDictLN_TCutG);
   G__get_linked_tagnum(&G__THistogratorDictLN_TPaveStats);
   G__get_linked_tagnum(&G__THistogratorDictLN_TPolyLine);
   G__get_linked_tagnum(&G__THistogratorDictLN_State_t);
   G__tagtable_setup(G__get_linked_tagnum(&G__THistogratorDictLN_THistogrator),sizeof(THistogrator),-1,62720,"Graphical histogram integrator base class",G__setup_memvarTHistogrator,G__setup_memfuncTHistogrator);
}
extern "C" void G__cpp_setupTHistogratorDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTHistogratorDict()");
  G__set_cpp_environmentTHistogratorDict();
  G__cpp_setup_tagtableTHistogratorDict();

  G__cpp_setup_inheritanceTHistogratorDict();

  G__cpp_setup_typetableTHistogratorDict();

  G__cpp_setup_memvarTHistogratorDict();

  G__cpp_setup_memfuncTHistogratorDict();
  G__cpp_setup_globalTHistogratorDict();
  G__cpp_setup_funcTHistogratorDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTHistogratorDict();
  return;
}
class G__cpp_setup_initTHistogratorDict {
  public:
    G__cpp_setup_initTHistogratorDict() { G__add_setup_func("THistogratorDict",(G__incsetup)(&G__cpp_setupTHistogratorDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTHistogratorDict() { G__remove_setup_func("THistogratorDict"); }
};
G__cpp_setup_initTHistogratorDict G__cpp_setup_initializerTHistogratorDict;

