/********************************************************************
* THistograteUtilDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error THistograteUtilDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTHistograteUtilDict();
extern void G__cpp_setup_inheritanceTHistograteUtilDict();
extern void G__cpp_setup_typetableTHistograteUtilDict();
extern void G__cpp_setup_memvarTHistograteUtilDict();
extern void G__cpp_setup_globalTHistograteUtilDict();
extern void G__cpp_setup_memfuncTHistograteUtilDict();
extern void G__cpp_setup_funcTHistograteUtilDict();
extern void G__set_cpp_environmentTHistograteUtilDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "THistograteUtil.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__THistograteUtilDictLN_TClass;
extern G__linked_taginfo G__THistograteUtilDictLN_TBuffer;
extern G__linked_taginfo G__THistograteUtilDictLN_TMemberInspector;
extern G__linked_taginfo G__THistograteUtilDictLN_TObject;
extern G__linked_taginfo G__THistograteUtilDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__THistograteUtilDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__THistograteUtilDictLN_TClassMenuItem;
extern G__linked_taginfo G__THistograteUtilDictLN_THistList;
extern G__linked_taginfo G__THistograteUtilDictLN_THistograteUtil;

/* STUB derived class for protected member access */
