//
// File generated by rootcint at Tue Apr 12 14:57:54 2005.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "THistogrator1Dict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"

#include "TCollectionProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void THistogrator1_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *THistogrator1_IsA(const void*);
   static void *new_THistogrator1(void *p = 0);
   static void *newArray_THistogrator1(Long_t size);
   static void delete_THistogrator1(void *p);
   static void deleteArray_THistogrator1(void *p);
   static void destruct_THistogrator1(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::THistogrator1*)
   {
      ::THistogrator1 *ptr = 0;
      static ::ROOT::TGenericClassInfo 
         instance("THistogrator1", ::THistogrator1::Class_Version(), "THistogrator1.h", 40,
                  typeid(::THistogrator1), DefineBehavior(ptr, ptr),
                  &::THistogrator1::Dictionary, &THistogrator1_IsA, 0,
                  sizeof(::THistogrator1) );
      instance.SetNew(&new_THistogrator1);
      instance.SetNewArray(&newArray_THistogrator1);
      instance.SetDelete(&delete_THistogrator1);
      instance.SetDeleteArray(&deleteArray_THistogrator1);
      instance.SetDestructor(&destruct_THistogrator1);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::THistogrator1*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *THistogrator1::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *THistogrator1::Class_Name()
{
   return "THistogrator1";
}

//______________________________________________________________________________
const char *THistogrator1::ImplFileName()
{
   return ::ROOT::GenerateInitInstance((const ::THistogrator1*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int THistogrator1::ImplFileLine()
{
   return ::ROOT::GenerateInitInstance((const ::THistogrator1*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void THistogrator1::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstance((const ::THistogrator1*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *THistogrator1::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstance((const ::THistogrator1*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void THistogrator1::Streamer(TBuffer &R__b)
{
   // Stream an object of class THistogrator1.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      THistogrator::Streamer(R__b);
      R__b >> ffirst_bin;
      R__b.CheckByteCount(R__s, R__c, THistogrator1::IsA());
   } else {
      R__c = R__b.WriteVersion(THistogrator1::IsA(), kTRUE);
      THistogrator::Streamer(R__b);
      R__b << ffirst_bin;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void THistogrator1::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class THistogrator1.

      TClass *R__cl = ::THistogrator1::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "ffirst_bin", &ffirst_bin);
      THistogrator::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *THistogrator1_IsA(const void *obj) {
      return ((::THistogrator1*)obj)->IsA();
   }
   // Wrappers around operator new
   static void *new_THistogrator1(void *p) {
      return  p ? new(p) ::THistogrator1 : new ::THistogrator1;
   }
   static void *newArray_THistogrator1(Long_t size) {
      return new ::THistogrator1[size];
   }
   // Wrapper around operator delete
   static void delete_THistogrator1(void *p) {
      delete ((::THistogrator1*)p);
   }
   static void deleteArray_THistogrator1(void *p) {
      delete [] ((::THistogrator1*)p);
   }
   static void destruct_THistogrator1(void *p) {
      typedef ::THistogrator1 current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::THistogrator1

/********************************************************
* THistogrator1Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableTHistogrator1Dict();

extern "C" void G__set_cpp_environmentTHistogrator1Dict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("THistogrator1.h");
  G__cpp_reset_tagtableTHistogrator1Dict();
}
class G__THistogrator1DictdOC_tag {};

void* operator new(size_t size,G__THistogrator1DictdOC_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__THistogrator1DictdOC_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_THistogrator1DictdOC() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevTHistogrator1Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* THistogrator1 */
static int G__THistogrator1Dict_318_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   THistogrator1 *p=NULL;
   if(G__getaryconstruct()) p=new THistogrator1[G__getaryconstruct()];
   else                    p=new THistogrator1;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   THistogrator1 *p=NULL;
      p = new THistogrator1(
(const char*)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(TH1*)G__int(libp->para[2]),(TH1*)G__int(libp->para[3]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->Delete();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->ExecuteButton1Up((double)G__double(libp->para[0]),(double)G__double(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->ExecuteClosed();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->ExecuteMotion((double)G__double(libp->para[0]),(double)G__double(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->Paint();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->SetFillColor((Color_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->SetFillStyle((Style_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->SetLineColor((Color_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->SetLineStyle((Style_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)THistogrator1::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistogrator1::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)THistogrator1::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      THistogrator1::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const THistogrator1*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator1*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistogrator1::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)THistogrator1::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistogrator1::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator1Dict_318_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)THistogrator1::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__THistogrator1Dict_318_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   THistogrator1 *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new THistogrator1(*(THistogrator1*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef THistogrator1 G__TTHistogrator1;
static int G__THistogrator1Dict_318_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (THistogrator1 *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (THistogrator1 *)((G__getstructoffset())+sizeof(THistogrator1)*i);
   else  delete (THistogrator1 *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__THistogrator1Dict_318_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   THistogrator1 *dest = (THistogrator1*)(G__getstructoffset());
   *dest = (*(THistogrator1*)libp->para[0].ref);
   const THistogrator1& obj = *dest;
   result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* THistogrator1 */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTHistogrator1Dict {
 public:
  G__Sizep2memfuncTHistogrator1Dict() {p=&G__Sizep2memfuncTHistogrator1Dict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTHistogrator1Dict::*p)();
};

size_t G__get_sizep2memfuncTHistogrator1Dict()
{
  G__Sizep2memfuncTHistogrator1Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTHistogrator1Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1))) {
     THistogrator1 *G__Lderived;
     G__Lderived=(THistogrator1*)0x1000;
     {
       THistogrator *G__Lpbase=(THistogrator*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1),G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1),G__get_linked_tagnum(&G__THistogrator1DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TAttFill *G__Lpbase=(TAttFill*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1),G__get_linked_tagnum(&G__THistogrator1DictLN_TAttFill),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TAttLine *G__Lpbase=(TAttLine*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1),G__get_linked_tagnum(&G__THistogrator1DictLN_TAttLine),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTHistogrator1Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__THistogrator1DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__THistogrator1DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THistogrator1DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__THistogrator1DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THistogrator1DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("Style_t",115,-1,0,
-1);
   G__setnewtype(-1,"Style number (short)",0);
   G__search_typename2("Color_t",115,-1,0,
-1);
   G__setnewtype(-1,"Color number (short)",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* THistogrator1 */
static void G__setup_memvarTHistogrator1(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1));
   { THistogrator1 *p; p=(THistogrator1*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,4,"ffirst_bin=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistogrator1DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTHistogrator1Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTHistogrator1(void) {
   /* THistogrator1 */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1));
   G__memfunc_setup("THistogrator1",1307,G__THistogrator1Dict_318_1_0,105,G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("THistogrator1",1307,G__THistogrator1Dict_318_2_0,105,G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1),-1,0,4,1,1,0,
"C - - 10 - name C - - 10 - title "
"U 'TH1' - 0 - h U 'TH1' - 0 - ah",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Delete",595,G__THistogrator1Dict_318_3_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteButton1Up",1605,G__THistogrator1Dict_318_4_0,121,-1,-1,0,2,1,1,0,
"d - - 0 - padx d - - 0 - pady",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteClosed",1325,G__THistogrator1Dict_318_5_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteMotion",1353,G__THistogrator1Dict_318_6_0,121,-1,-1,0,2,1,1,0,
"d - - 0 - padx d - - 0 - pady",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Paint",508,G__THistogrator1Dict_318_7_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetFillColor",1202,G__THistogrator1Dict_318_8_0,121,-1,-1,0,1,1,1,0,"s - 'Color_t' 0 - fcolor",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetFillStyle",1220,G__THistogrator1Dict_318_9_0,121,-1,-1,0,1,1,1,0,"s - 'Style_t' 0 - fstyle",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetLineColor",1203,G__THistogrator1Dict_318_0_1,121,-1,-1,0,1,1,1,0,"s - 'Color_t' 0 - lcolor",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetLineStyle",1221,G__THistogrator1Dict_318_1_1,121,-1,-1,0,1,1,1,0,"s - 'Style_t' 0 - lstyle",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("CreateStats",1123,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SelectBins",1004,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"i - - 0 - bin1 i - - 0 - bin2",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("UnselectAll",1116,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("UpdateStats",1138,(G__InterfaceMethod)NULL,121,-1,-1,0,4,1,4,0,
"d - 'Stat_t' 0 - sum d - - 0 - integral "
"d - - 0 - left d - - 0 - right",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__THistogrator1Dict_318_7_1,85,G__get_linked_tagnum(&G__THistogrator1DictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)(TClass* (*)())(&THistogrator1::Class),0);
   G__memfunc_setup("Class_Name",982,G__THistogrator1Dict_318_8_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistogrator1::Class_Name),0);
   G__memfunc_setup("Class_Version",1339,G__THistogrator1Dict_318_9_1,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)(Version_t (*)())(&THistogrator1::Class_Version),0);
   G__memfunc_setup("Dictionary",1046,G__THistogrator1Dict_318_0_2,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(void (*)())(&THistogrator1::Dictionary),0);
   G__memfunc_setup("IsA",253,G__THistogrator1Dict_318_1_2,85,G__get_linked_tagnum(&G__THistogrator1DictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__THistogrator1Dict_318_2_2,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__THistogrator1Dict_318_3_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__THistogrator1Dict_318_4_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__THistogrator1Dict_318_5_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistogrator1::DeclFileName),0);
   G__memfunc_setup("ImplFileLine",1178,G__THistogrator1Dict_318_6_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&THistogrator1::ImplFileLine),0);
   G__memfunc_setup("ImplFileName",1171,G__THistogrator1Dict_318_7_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistogrator1::ImplFileName),0);
   G__memfunc_setup("DeclFileLine",1152,G__THistogrator1Dict_318_8_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&THistogrator1::DeclFileLine),0);
   // automatic copy constructor
   G__memfunc_setup("THistogrator1",1307,G__THistogrator1Dict_318_9_2,(int)('i'),G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1),-1,0,1,1,1,0,"u 'THistogrator1' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~THistogrator1",1433,G__THistogrator1Dict_318_0_3,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic assignment operator
   G__memfunc_setup("operator=",937,G__THistogrator1Dict_318_1_3,(int)('u'),G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1),-1,1,1,1,1,0,"u 'THistogrator1' - 11 - -",(char*)NULL,(void*)NULL,0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTHistogrator1Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTHistogrator1Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTHistogrator1Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__THistogrator1DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__THistogrator1DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__THistogrator1DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__THistogrator1DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__THistogrator1DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__THistogrator1DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__THistogrator1DictLN_TAttLine = { "TAttLine" , 99 , -1 };
G__linked_taginfo G__THistogrator1DictLN_TAttFill = { "TAttFill" , 99 , -1 };
G__linked_taginfo G__THistogrator1DictLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__THistogrator1DictLN_THistogrator = { "THistogrator" , 99 , -1 };
G__linked_taginfo G__THistogrator1DictLN_THistogrator1 = { "THistogrator1" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTHistogrator1Dict() {
  G__THistogrator1DictLN_TClass.tagnum = -1 ;
  G__THistogrator1DictLN_TBuffer.tagnum = -1 ;
  G__THistogrator1DictLN_TMemberInspector.tagnum = -1 ;
  G__THistogrator1DictLN_TObject.tagnum = -1 ;
  G__THistogrator1DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__THistogrator1DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__THistogrator1DictLN_TAttLine.tagnum = -1 ;
  G__THistogrator1DictLN_TAttFill.tagnum = -1 ;
  G__THistogrator1DictLN_TH1.tagnum = -1 ;
  G__THistogrator1DictLN_THistogrator.tagnum = -1 ;
  G__THistogrator1DictLN_THistogrator1.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTHistogrator1Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__THistogrator1DictLN_TClass);
   G__get_linked_tagnum(&G__THistogrator1DictLN_TBuffer);
   G__get_linked_tagnum(&G__THistogrator1DictLN_TMemberInspector);
   G__get_linked_tagnum(&G__THistogrator1DictLN_TObject);
   G__get_linked_tagnum(&G__THistogrator1DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__THistogrator1DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__THistogrator1DictLN_TAttLine);
   G__get_linked_tagnum(&G__THistogrator1DictLN_TAttFill);
   G__get_linked_tagnum(&G__THistogrator1DictLN_TH1);
   G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator);
   G__tagtable_setup(G__get_linked_tagnum(&G__THistogrator1DictLN_THistogrator1),sizeof(THistogrator1),-1,61696,(char*)NULL,G__setup_memvarTHistogrator1,G__setup_memfuncTHistogrator1);
}
extern "C" void G__cpp_setupTHistogrator1Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTHistogrator1Dict()");
  G__set_cpp_environmentTHistogrator1Dict();
  G__cpp_setup_tagtableTHistogrator1Dict();

  G__cpp_setup_inheritanceTHistogrator1Dict();

  G__cpp_setup_typetableTHistogrator1Dict();

  G__cpp_setup_memvarTHistogrator1Dict();

  G__cpp_setup_memfuncTHistogrator1Dict();
  G__cpp_setup_globalTHistogrator1Dict();
  G__cpp_setup_funcTHistogrator1Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTHistogrator1Dict();
  return;
}
class G__cpp_setup_initTHistogrator1Dict {
  public:
    G__cpp_setup_initTHistogrator1Dict() { G__add_setup_func("THistogrator1Dict",(G__incsetup)(&G__cpp_setupTHistogrator1Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTHistogrator1Dict() { G__remove_setup_func("THistogrator1Dict"); }
};
G__cpp_setup_initTHistogrator1Dict G__cpp_setup_initializerTHistogrator1Dict;

