/********************************************************************
* THistogratorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error THistogratorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTHistogratorDict();
extern void G__cpp_setup_inheritanceTHistogratorDict();
extern void G__cpp_setup_typetableTHistogratorDict();
extern void G__cpp_setup_memvarTHistogratorDict();
extern void G__cpp_setup_globalTHistogratorDict();
extern void G__cpp_setup_memfuncTHistogratorDict();
extern void G__cpp_setup_funcTHistogratorDict();
extern void G__set_cpp_environmentTHistogratorDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "THistogrator.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__THistogratorDictLN_G__ulonglong;
extern G__linked_taginfo G__THistogratorDictLN_G__longlong;
extern G__linked_taginfo G__THistogratorDictLN_TClass;
extern G__linked_taginfo G__THistogratorDictLN_TBuffer;
extern G__linked_taginfo G__THistogratorDictLN_TMemberInspector;
extern G__linked_taginfo G__THistogratorDictLN_TObject;
extern G__linked_taginfo G__THistogratorDictLN_TList;
extern G__linked_taginfo G__THistogratorDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__THistogratorDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__THistogratorDictLN_TAttFill;
extern G__linked_taginfo G__THistogratorDictLN_TAttLine;
extern G__linked_taginfo G__THistogratorDictLN_TQObjSender;
extern G__linked_taginfo G__THistogratorDictLN_TCanvas;
extern G__linked_taginfo G__THistogratorDictLN_TPad;
extern G__linked_taginfo G__THistogratorDictLN_TH1;
extern G__linked_taginfo G__THistogratorDictLN_TCutG;
extern G__linked_taginfo G__THistogratorDictLN_TPaveStats;
extern G__linked_taginfo G__THistogratorDictLN_TPolyLine;
extern G__linked_taginfo G__THistogratorDictLN_State_t;
extern G__linked_taginfo G__THistogratorDictLN_THistogrator;

/* STUB derived class for protected member access */
