//
// File generated by rootcint at Tue Apr 12 14:58:00 2005.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "THistogrator2Dict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"

#include "TCollectionProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void THistogrator2_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *THistogrator2_IsA(const void*);
   static void *new_THistogrator2(void *p = 0);
   static void *newArray_THistogrator2(Long_t size);
   static void delete_THistogrator2(void *p);
   static void deleteArray_THistogrator2(void *p);
   static void destruct_THistogrator2(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::THistogrator2*)
   {
      ::THistogrator2 *ptr = 0;
      static ::ROOT::TGenericClassInfo 
         instance("THistogrator2", ::THistogrator2::Class_Version(), "THistogrator2.h", 44,
                  typeid(::THistogrator2), DefineBehavior(ptr, ptr),
                  &::THistogrator2::Dictionary, &THistogrator2_IsA, 0,
                  sizeof(::THistogrator2) );
      instance.SetNew(&new_THistogrator2);
      instance.SetNewArray(&newArray_THistogrator2);
      instance.SetDelete(&delete_THistogrator2);
      instance.SetDeleteArray(&deleteArray_THistogrator2);
      instance.SetDestructor(&destruct_THistogrator2);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::THistogrator2*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *THistogrator2::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *THistogrator2::Class_Name()
{
   return "THistogrator2";
}

//______________________________________________________________________________
const char *THistogrator2::ImplFileName()
{
   return ::ROOT::GenerateInitInstance((const ::THistogrator2*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int THistogrator2::ImplFileLine()
{
   return ::ROOT::GenerateInitInstance((const ::THistogrator2*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void THistogrator2::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstance((const ::THistogrator2*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *THistogrator2::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstance((const ::THistogrator2*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void THistogrator2::Streamer(TBuffer &R__b)
{
   // Stream an object of class THistogrator2.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      THistogrator::Streamer(R__b);
      R__b >> fBinShadeList;
      R__b >> fLastIntegral;
      R__b >> fLastPoint;
      R__b >> fLastSum;
      R__b >> fLine;
      R__b.CheckByteCount(R__s, R__c, THistogrator2::IsA());
   } else {
      R__c = R__b.WriteVersion(THistogrator2::IsA(), kTRUE);
      THistogrator::Streamer(R__b);
      R__b << fBinShadeList;
      R__b << fLastIntegral;
      R__b << fLastPoint;
      R__b << fLastSum;
      R__b << fLine;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void THistogrator2::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class THistogrator2.

      TClass *R__cl = ::THistogrator2::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fBinShadeList", &fBinShadeList);
      R__insp.Inspect(R__cl, R__parent, "fLastIntegral", &fLastIntegral);
      R__insp.Inspect(R__cl, R__parent, "fLastPoint", &fLastPoint);
      R__insp.Inspect(R__cl, R__parent, "fLastSum", &fLastSum);
      R__insp.Inspect(R__cl, R__parent, "*fLine", &fLine);
      THistogrator::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *THistogrator2_IsA(const void *obj) {
      return ((::THistogrator2*)obj)->IsA();
   }
   // Wrappers around operator new
   static void *new_THistogrator2(void *p) {
      return  p ? new(p) ::THistogrator2 : new ::THistogrator2;
   }
   static void *newArray_THistogrator2(Long_t size) {
      return new ::THistogrator2[size];
   }
   // Wrapper around operator delete
   static void delete_THistogrator2(void *p) {
      delete ((::THistogrator2*)p);
   }
   static void deleteArray_THistogrator2(void *p) {
      delete [] ((::THistogrator2*)p);
   }
   static void destruct_THistogrator2(void *p) {
      typedef ::THistogrator2 current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::THistogrator2

/********************************************************
* THistogrator2Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableTHistogrator2Dict();

extern "C" void G__set_cpp_environmentTHistogrator2Dict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("THistogrator2.h");
  G__cpp_reset_tagtableTHistogrator2Dict();
}
class G__THistogrator2DictdOC_tag {};

void* operator new(size_t size,G__THistogrator2DictdOC_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__THistogrator2DictdOC_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_THistogrator2DictdOC() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevTHistogrator2Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* THistogrator2 */
static int G__THistogrator2Dict_315_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   THistogrator2 *p=NULL;
   if(G__getaryconstruct()) p=new THistogrator2[G__getaryconstruct()];
   else                    p=new THistogrator2;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   THistogrator2 *p=NULL;
      p = new THistogrator2(
(const char*)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(TH1*)G__int(libp->para[2]),(TH1*)G__int(libp->para[3]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->DelCut();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->Delete();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->ExecuteButton1Up((double)G__double(libp->para[0]),(double)G__double(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->ExecuteClosed();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->ExecuteKey();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->ExecuteMotion((double)G__double(libp->para[0]),(double)G__double(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((THistogrator2*)(G__getstructoffset()))->GetPoly((TObject*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->Paint();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->SetCut(*(TCutG*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->SetFillColor((Color_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->SetFillStyle((Style_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->SetLineColor((Color_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->SetLineStyle((Style_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)THistogrator2::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistogrator2::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)THistogrator2::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      THistogrator2::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const THistogrator2*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((THistogrator2*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistogrator2::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)THistogrator2::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_2_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)THistogrator2::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THistogrator2Dict_315_3_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)THistogrator2::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__THistogrator2Dict_315_4_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   THistogrator2 *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new THistogrator2(*(THistogrator2*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef THistogrator2 G__TTHistogrator2;
static int G__THistogrator2Dict_315_5_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (THistogrator2 *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (THistogrator2 *)((G__getstructoffset())+sizeof(THistogrator2)*i);
   else  delete (THistogrator2 *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__THistogrator2Dict_315_6_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   THistogrator2 *dest = (THistogrator2*)(G__getstructoffset());
   *dest = (*(THistogrator2*)libp->para[0].ref);
   const THistogrator2& obj = *dest;
   result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* THistogrator2 */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTHistogrator2Dict {
 public:
  G__Sizep2memfuncTHistogrator2Dict() {p=&G__Sizep2memfuncTHistogrator2Dict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTHistogrator2Dict::*p)();
};

size_t G__get_sizep2memfuncTHistogrator2Dict()
{
  G__Sizep2memfuncTHistogrator2Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTHistogrator2Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2))) {
     THistogrator2 *G__Lderived;
     G__Lderived=(THistogrator2*)0x1000;
     {
       THistogrator *G__Lpbase=(THistogrator*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2),G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2),G__get_linked_tagnum(&G__THistogrator2DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TAttFill *G__Lpbase=(TAttFill*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2),G__get_linked_tagnum(&G__THistogrator2DictLN_TAttFill),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TAttLine *G__Lpbase=(TAttLine*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2),G__get_linked_tagnum(&G__THistogrator2DictLN_TAttLine),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTHistogrator2Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__THistogrator2DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__THistogrator2DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THistogrator2DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__THistogrator2DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THistogrator2DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.41 2004/11/19 07:25:43 brun Exp $",0);
   G__search_typename2("Style_t",115,-1,0,
-1);
   G__setnewtype(-1,"Style number (short)",0);
   G__search_typename2("Color_t",115,-1,0,
-1);
   G__setnewtype(-1,"Color number (short)",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* THistogrator2 */
static void G__setup_memvarTHistogrator2(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2));
   { THistogrator2 *p; p=(THistogrator2*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistogrator2DictLN_TList),-1,-1,4,"fBinShadeList=",0,"List of shaded bin polylines");
   G__memvar_setup((void*)NULL,100,0,0,-1,-1,-1,4,"fLastIntegral=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,4,"fLastPoint=",0,"Point number of last point added to fCut");
   G__memvar_setup((void*)NULL,100,0,0,-1,G__defined_typename("Stat_t"),-1,4,"fLastSum=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistogrator2DictLN_TLine),-1,-1,4,"fLine=",0,"Line from last point in fCut to mouse position");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__THistogrator2DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTHistogrator2Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTHistogrator2(void) {
   /* THistogrator2 */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2));
   G__memfunc_setup("THistogrator2",1308,G__THistogrator2Dict_315_1_0,105,G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("THistogrator2",1308,G__THistogrator2Dict_315_2_0,105,G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2),-1,0,4,1,1,0,
"C - - 10 - name C - - 10 - title "
"U 'TH1' - 0 - h U 'TH1' - 0 - ah",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DelCut",577,G__THistogrator2Dict_315_3_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Delete",595,G__THistogrator2Dict_315_4_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteButton1Up",1605,G__THistogrator2Dict_315_5_0,121,-1,-1,0,2,1,1,0,
"d - - 0 - padx d - - 0 - pady",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteClosed",1325,G__THistogrator2Dict_315_6_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteKey",1020,G__THistogrator2Dict_315_7_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteMotion",1353,G__THistogrator2Dict_315_8_0,121,-1,-1,0,2,1,1,0,
"d - - 0 - padx d - - 0 - pady",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetPoly",708,G__THistogrator2Dict_315_9_0,85,G__get_linked_tagnum(&G__THistogrator2DictLN_TPolyLine),-1,0,1,1,1,0,"U 'TObject' - 0 - p",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Paint",508,G__THistogrator2Dict_315_0_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetCut",600,G__THistogrator2Dict_315_1_1,121,-1,-1,0,1,1,1,0,"u 'TCutG' - 11 - cut",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetFillColor",1202,G__THistogrator2Dict_315_2_1,121,-1,-1,0,1,1,1,0,"s - 'Color_t' 0 - fcolor",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetFillStyle",1220,G__THistogrator2Dict_315_3_1,121,-1,-1,0,1,1,1,0,"s - 'Style_t' 0 - fstyle",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetLineColor",1203,G__THistogrator2Dict_315_4_1,121,-1,-1,0,1,1,1,0,"s - 'Color_t' 0 - fcolor",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetLineStyle",1221,G__THistogrator2Dict_315_5_1,121,-1,-1,0,1,1,1,0,"s - 'Style_t' 0 - fstyle",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("CreateBinShade",1362,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"i - - 0 - binx i - - 0 - biny",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CreateStats",1123,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SelectBins",1004,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("UnselectAll",1116,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("UpdateStats",1138,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"d - 'Stat_t' 0 - sum d - - 0 - integral",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__THistogrator2Dict_315_2_2,85,G__get_linked_tagnum(&G__THistogrator2DictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)(TClass* (*)())(&THistogrator2::Class),0);
   G__memfunc_setup("Class_Name",982,G__THistogrator2Dict_315_3_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistogrator2::Class_Name),0);
   G__memfunc_setup("Class_Version",1339,G__THistogrator2Dict_315_4_2,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)(Version_t (*)())(&THistogrator2::Class_Version),0);
   G__memfunc_setup("Dictionary",1046,G__THistogrator2Dict_315_5_2,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(void (*)())(&THistogrator2::Dictionary),0);
   G__memfunc_setup("IsA",253,G__THistogrator2Dict_315_6_2,85,G__get_linked_tagnum(&G__THistogrator2DictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__THistogrator2Dict_315_7_2,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__THistogrator2Dict_315_8_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__THistogrator2Dict_315_9_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__THistogrator2Dict_315_0_3,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistogrator2::DeclFileName),0);
   G__memfunc_setup("ImplFileLine",1178,G__THistogrator2Dict_315_1_3,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&THistogrator2::ImplFileLine),0);
   G__memfunc_setup("ImplFileName",1171,G__THistogrator2Dict_315_2_3,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&THistogrator2::ImplFileName),0);
   G__memfunc_setup("DeclFileLine",1152,G__THistogrator2Dict_315_3_3,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&THistogrator2::DeclFileLine),0);
   // automatic copy constructor
   G__memfunc_setup("THistogrator2",1308,G__THistogrator2Dict_315_4_3,(int)('i'),G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2),-1,0,1,1,1,0,"u 'THistogrator2' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~THistogrator2",1434,G__THistogrator2Dict_315_5_3,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic assignment operator
   G__memfunc_setup("operator=",937,G__THistogrator2Dict_315_6_3,(int)('u'),G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2),-1,1,1,1,1,0,"u 'THistogrator2' - 11 - -",(char*)NULL,(void*)NULL,0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTHistogrator2Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTHistogrator2Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTHistogrator2Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__THistogrator2DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_TAttLine = { "TAttLine" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_TAttFill = { "TAttFill" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_TPolyLine = { "TPolyLine" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_TCutG = { "TCutG" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_TLine = { "TLine" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_THistogrator = { "THistogrator" , 99 , -1 };
G__linked_taginfo G__THistogrator2DictLN_THistogrator2 = { "THistogrator2" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTHistogrator2Dict() {
  G__THistogrator2DictLN_TClass.tagnum = -1 ;
  G__THistogrator2DictLN_TBuffer.tagnum = -1 ;
  G__THistogrator2DictLN_TMemberInspector.tagnum = -1 ;
  G__THistogrator2DictLN_TObject.tagnum = -1 ;
  G__THistogrator2DictLN_TList.tagnum = -1 ;
  G__THistogrator2DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__THistogrator2DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__THistogrator2DictLN_TAttLine.tagnum = -1 ;
  G__THistogrator2DictLN_TAttFill.tagnum = -1 ;
  G__THistogrator2DictLN_TPolyLine.tagnum = -1 ;
  G__THistogrator2DictLN_TH1.tagnum = -1 ;
  G__THistogrator2DictLN_TCutG.tagnum = -1 ;
  G__THistogrator2DictLN_TLine.tagnum = -1 ;
  G__THistogrator2DictLN_THistogrator.tagnum = -1 ;
  G__THistogrator2DictLN_THistogrator2.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTHistogrator2Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__THistogrator2DictLN_TClass);
   G__get_linked_tagnum(&G__THistogrator2DictLN_TBuffer);
   G__get_linked_tagnum(&G__THistogrator2DictLN_TMemberInspector);
   G__get_linked_tagnum(&G__THistogrator2DictLN_TObject);
   G__get_linked_tagnum(&G__THistogrator2DictLN_TList);
   G__get_linked_tagnum(&G__THistogrator2DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__THistogrator2DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__THistogrator2DictLN_TAttLine);
   G__get_linked_tagnum(&G__THistogrator2DictLN_TAttFill);
   G__get_linked_tagnum(&G__THistogrator2DictLN_TPolyLine);
   G__get_linked_tagnum(&G__THistogrator2DictLN_TH1);
   G__get_linked_tagnum(&G__THistogrator2DictLN_TCutG);
   G__get_linked_tagnum(&G__THistogrator2DictLN_TLine);
   G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator);
   G__tagtable_setup(G__get_linked_tagnum(&G__THistogrator2DictLN_THistogrator2),sizeof(THistogrator2),-1,62720,(char*)NULL,G__setup_memvarTHistogrator2,G__setup_memfuncTHistogrator2);
}
extern "C" void G__cpp_setupTHistogrator2Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTHistogrator2Dict()");
  G__set_cpp_environmentTHistogrator2Dict();
  G__cpp_setup_tagtableTHistogrator2Dict();

  G__cpp_setup_inheritanceTHistogrator2Dict();

  G__cpp_setup_typetableTHistogrator2Dict();

  G__cpp_setup_memvarTHistogrator2Dict();

  G__cpp_setup_memfuncTHistogrator2Dict();
  G__cpp_setup_globalTHistogrator2Dict();
  G__cpp_setup_funcTHistogrator2Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTHistogrator2Dict();
  return;
}
class G__cpp_setup_initTHistogrator2Dict {
  public:
    G__cpp_setup_initTHistogrator2Dict() { G__add_setup_func("THistogrator2Dict",(G__incsetup)(&G__cpp_setupTHistogrator2Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTHistogrator2Dict() { G__remove_setup_func("THistogrator2Dict"); }
};
G__cpp_setup_initTHistogrator2Dict G__cpp_setup_initializerTHistogrator2Dict;

