/********************************************************************
* THistogrator1Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error THistogrator1Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTHistogrator1Dict();
extern void G__cpp_setup_inheritanceTHistogrator1Dict();
extern void G__cpp_setup_typetableTHistogrator1Dict();
extern void G__cpp_setup_memvarTHistogrator1Dict();
extern void G__cpp_setup_globalTHistogrator1Dict();
extern void G__cpp_setup_memfuncTHistogrator1Dict();
extern void G__cpp_setup_funcTHistogrator1Dict();
extern void G__set_cpp_environmentTHistogrator1Dict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "THistogrator1.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__THistogrator1DictLN_TClass;
extern G__linked_taginfo G__THistogrator1DictLN_TBuffer;
extern G__linked_taginfo G__THistogrator1DictLN_TMemberInspector;
extern G__linked_taginfo G__THistogrator1DictLN_TObject;
extern G__linked_taginfo G__THistogrator1DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__THistogrator1DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__THistogrator1DictLN_TAttLine;
extern G__linked_taginfo G__THistogrator1DictLN_TAttFill;
extern G__linked_taginfo G__THistogrator1DictLN_TH1;
extern G__linked_taginfo G__THistogrator1DictLN_THistogrator;
extern G__linked_taginfo G__THistogrator1DictLN_THistogrator1;

/* STUB derived class for protected member access */
