/********************************************************************
* THistListDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error THistListDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTHistListDict();
extern void G__cpp_setup_inheritanceTHistListDict();
extern void G__cpp_setup_typetableTHistListDict();
extern void G__cpp_setup_memvarTHistListDict();
extern void G__cpp_setup_globalTHistListDict();
extern void G__cpp_setup_memfuncTHistListDict();
extern void G__cpp_setup_funcTHistListDict();
extern void G__set_cpp_environmentTHistListDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "THistList.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__THistListDictLN_TObject;
extern G__linked_taginfo G__THistListDictLN_TList;
extern G__linked_taginfo G__THistListDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__THistListDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__THistListDictLN_THistogrator;
extern G__linked_taginfo G__THistListDictLN_THistList;

/* STUB derived class for protected member access */
