/********************************************************************
* THistogrator2Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error THistogrator2Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTHistogrator2Dict();
extern void G__cpp_setup_inheritanceTHistogrator2Dict();
extern void G__cpp_setup_typetableTHistogrator2Dict();
extern void G__cpp_setup_memvarTHistogrator2Dict();
extern void G__cpp_setup_globalTHistogrator2Dict();
extern void G__cpp_setup_memfuncTHistogrator2Dict();
extern void G__cpp_setup_funcTHistogrator2Dict();
extern void G__set_cpp_environmentTHistogrator2Dict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "THistogrator2.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__THistogrator2DictLN_TClass;
extern G__linked_taginfo G__THistogrator2DictLN_TBuffer;
extern G__linked_taginfo G__THistogrator2DictLN_TMemberInspector;
extern G__linked_taginfo G__THistogrator2DictLN_TObject;
extern G__linked_taginfo G__THistogrator2DictLN_TList;
extern G__linked_taginfo G__THistogrator2DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__THistogrator2DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__THistogrator2DictLN_TAttLine;
extern G__linked_taginfo G__THistogrator2DictLN_TAttFill;
extern G__linked_taginfo G__THistogrator2DictLN_TPolyLine;
extern G__linked_taginfo G__THistogrator2DictLN_TH1;
extern G__linked_taginfo G__THistogrator2DictLN_TCutG;
extern G__linked_taginfo G__THistogrator2DictLN_TLine;
extern G__linked_taginfo G__THistogrator2DictLN_THistogrator;
extern G__linked_taginfo G__THistogrator2DictLN_THistogrator2;

/* STUB derived class for protected member access */
